name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: OS info
        shell: bash
        run: |
          cat /etc/lsb-release

      - name: Install Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Python info
        shell: bash
        run: |
          echo $(python --version) at $(which python)

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
          pip install -U pip
          pip install -r ./requirements-dev.txt

      - name: Run tests
        shell: bash
        run: |
          nox --session test

      - name: Run linting
        shell: bash
        run: |
          nox --session lint
      
      - name: Install publish dependencies
        shell: bash
        run: |
          pip install setuptools wheel twine
  
      - name: Build and publish
        shell: bash
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
